services:
  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - spring-msvcs
    environment:
      SPRING_PROFILES_ACTIVE: git

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - spring-msvcs

  msvc-customer:
    container_name: msvc-customer
    build:
      context: ./msvc-customer
      dockerfile: Dockerfile
    ports:
      - "18032:18032"
    depends_on:
      - postgres-msvc-customers
      - redis-msvc-customers
      - eureka-server
      - config-server
    networks:
      - spring-msvcs

  msvc-orders:
    container_name: msvc-orders
    build:
      context: ./msvc-orders
      dockerfile: Dockerfile
    ports:
      - "18033:18033"
    depends_on:
      - mongodb-msvc-orders
      - redis-msvc-orders
      - eureka-server
      - config-server
    networks:
      - spring-msvcs

  msvc-details-order:
    container_name: msvc-details-order
    build:
      context: ./msvc-details-order
      dockerfile: Dockerfile
    ports:
      - "18034:18034"
    depends_on:
      - mongodb-msvc-details-order
      - redis-msvc-details-order
      - eureka-server
      - config-server
    networks:
      - spring-msvcs

  msvc-products:
    container_name: msvc-products
    build:
      context: ./msvc-products
      dockerfile: Dockerfile
    ports:
      - "18031:18031"
    depends_on:
      - mysql-msvc-products
      - redis-msvc-products
      - eureka-server
      - config-server
    networks:
      - spring-msvcs

  msvc-oauth:
    container_name: msvc-oauth
    build:
      context: ./msvc-oauth
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    depends_on:
      - redis-msvc-oauth
      - eureka-server
      - config-server
    networks:
      - spring-msvcs

  gateway:
    container_name: gateway
    build:
      context: ./msvc-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server
      - msvc-oauth
    networks:
      - spring-msvcs

  postgres-msvc-customers:
    container_name: postgres-msvc-customers
    image: postgres:15
    environment:
      POSTGRES_DB: msvc-customers
      POSTGRES_USER: gad-dev
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_msvc-customers:/var/lib/postgresql/data
    networks:
      - spring-msvcs

  redis-msvc-customers:
    container_name: redis-msvc-customers
    image: redis:7.0-alpine
    ports:
      - "6382:6379"
    volumes:
      - redis_data_msvc-customers:/data
    networks:
      - spring-msvcs

  mongodb-msvc-orders:
    container_name: mongodb-msvc-orders
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: gad-dev
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: msvc-orders
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_orders:/data/db
    networks:
      - spring-msvcs

  redis-msvc-orders:
    container_name: redis-msvc-orders
    image: redis:7.0-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data_msvc-orders:/data
    networks:
      - spring-msvcs

  mongodb-msvc-details-order:
    container_name: mongodb-msvc-details-order
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: gad-dev
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: msvc-details-order
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_details:/data/db
    networks:
      - spring-msvcs

  redis-msvc-details-order:
    container_name: redis-msvc-details-order
    image: redis:7.0-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data_msvc-details-order:/data
    networks:
      - spring-msvcs

  mysql-msvc-products:
    container_name: mysql-msvc-products
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: msvc-products
      MYSQL_USER: gad-dev
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_msvc-products:/var/lib/mysql
    networks:
      - spring-msvcs

  redis-msvc-products:
    container_name: redis-msvc-products
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_msvc-products:/data
    networks:
      - spring-msvcs

  redis-msvc-oauth:
    container_name: redis-msvc-oauth
    image: redis:7.0-alpine
    ports:
      - "6383:6379"
    volumes:
      - redis_data_msvc-oauth:/data
    networks:
        - spring-msvcs

networks:
  spring-msvcs:
    external: true
    name: spring-msvcs

volumes:
  postgres_data_msvc-customers:
  redis_data_msvc-customers:
  mongodb_data_orders:
  redis_data_msvc-orders:
  mongodb_data_details:
  redis_data_msvc-details-order:
  mysql_data_msvc-products:
  redis_data_msvc-products:
  redis_data_msvc-oauth: