services:
  postgres-msvc-customers:
    image: postgres:15
    container_name: postgres-msvc-customers
    restart: always
    environment:
      POSTGRES_DB: msvc-customers
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: gad-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_msvc-customers:/var/lib/postgresql/data

  redis-msvc-customers:
    image: redis:7.0-alpine
    container_name: redis-msvc-customers
    restart: always
    ports:
      - "6382:6379"
    volumes:
      - redis_data_msvc-customers:/data
    depends_on:
      - postgres-msvc-customers

volumes:
  postgres_data_msvc-customers:
  redis_data_msvc-customers: