INSERT INTO products (name, price, stock) VALUES ('iPhone 13', 999.99, 50);
INSERT INTO products (name, price, stock) VALUES ('Samsung Galaxy S21', 799.99, 75);
INSERT INTO products (name, price, stock) VALUES ('MacBook Pro', 1299.99, 30);
INSERT INTO products (name, price, stock) VALUES ('Dell XPS 13', 999.99, 40);
INSERT INTO products (name, price, stock) VALUES ('Sony WH-1000XM4', 349.99, 100);
INSERT INTO products (name, price, stock) VALUES ('Apple Watch Series 7', 399.99, 60);
INSERT INTO products (name, price, stock) VALUES ('iPad Pro', 799.99, 45);
INSERT INTO products (name, price, stock) VALUES ('Amazon Echo Dot', 49.99, 200);
INSERT INTO products (name, price, stock) VALUES ('Google Nest Hub', 89.99, 150);
INSERT INTO products (name, price, stock) VALUES ('PlayStation 5', 499.99, 20);
INSERT INTO products (name, price, stock) VALUES ('Xbox Series X', 499.99, 25);
INSERT INTO products (name, price, stock) VALUES ('Nintendo Switch', 299.99, 80);
INSERT INTO products (name, price, stock) VALUES ('GoPro HERO9', 399.99, 35);
INSERT INTO products (name, price, stock) VALUES ('Canon EOS R5', 3899.99, 10);
INSERT INTO products (name, price, stock) VALUES ('Bose QuietComfort 35 II', 299.99, 90);
INSERT INTO products (name, price, stock) VALUES ('Kindle Paperwhite', 129.99, 120);
INSERT INTO products (name, price, stock) VALUES ('Fitbit Charge 4', 149.99, 70);
INSERT INTO products (name, price, stock) VALUES ('Roku Streaming Stick+', 49.99, 110);
INSERT INTO products (name, price, stock) VALUES ('Apple AirPods Pro', 249.99, 85);
INSERT INTO products (name, price, stock) VALUES ('Samsung Galaxy Tab S7', 649.99, 55);