spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  cloud:
    config:
      enabled: false
  flyway:
    enabled: false
eureka:
  client:
    enabled: false
custom:
  path: api/v1