services:
  mongodb-msvc-orders:
    image: mongo:8.0
    container_name: mongodb-msvc-orders
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: gad-dev
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: msvc-orders
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_orders:/data/db

  redis-msvc-orders:
    image: redis:7.0-alpine
    container_name: redis-msvc-orders
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - redis_data_msvc-orders:/data
    depends_on:
      - mongodb-msvc-orders

volumes:
  mongodb_data_orders:
    driver: local
  redis_data_msvc-orders:
