spring:
  profiles:
    active: git
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true