spring:
  datasource:
    url: jdbc:mysql://mysql-msvc-products:3306/msvc-products
    username: gad-dev
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2000
      client-type: jedis
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      file: ./msvc-products/compose.yaml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 18031 #${PORT:0} for dynamic port

custom:
  path: /api/v1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true