spring:
  security:
    oauth2:
      authorization server:
        issuer: http://localhost:9100
    cache:
      type: redis
    data:
      redis:
        host: localhost
        port: 6383
        connect-timeout: 2000
        client-type: jedis
  docker:
    compose:
      file: ./msvc-oauth/compose.yaml

server:
  port: 9100
  hostname: 127.0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

custom:
  path: /api/v1

rsa:
  key:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAredepgy3Z3iL/xl48Bu52B4R8Zd8ZgFZeTOGl89v7Z3QI9QlTVXtkE4LbaUuAgQrByDi0Hp5uqGgQi1iYOaV/bQW0rO1uv0QmIXER65XQzzlomR+nYDEDUCBxc0PCYXv+iKlLxVE2EtQ+PYICagqVM93hEfqYNcuGCLD39bqm2Z3VphbBeEq9XIbjDQE1RqxoFXWUUvD1ivmBY/kCmcIntKKQqUPpy9VdNFFy8IEAEbmO8uiquvoTyACg3wmkhnGdfaTHSdWwg2y1iBN5YWMDozg8CuVHO2FDJu83FlpBlhjrcgo8N+ANQfRVs2gwHyHM3+xYyijj5qoryBH+xNpqwIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCt516mDLdneIv/GXjwG7nYHhHxl3xmAVl5M4aXz2/tndAj1CVNVe2QTgttpS4CBCsHIOLQenm6oaBCLWJg5pX9tBbSs7W6/RCYhcRHrldDPOWiZH6dgMQNQIHFzQ8Jhe/6IqUvFUTYS1D49ggJqCpUz3eER+pg1y4YIsPf1uqbZndWmFsF4Sr1chuMNATVGrGgVdZRS8PWK+YFj+QKZwie0opCpQ+nL1V00UXLwgQARuY7y6Kq6+hPIAKDfCaSGcZ19pMdJ1bCDbLWIE3lhYwOjODwK5Uc7YUMm7zcWWkGWGOtyCjw34A1B9FWzaDAfIczf7FjKKOPmqivIEf7E2mrAgMBAAECggEASvGBvYePZlzx4A7HKpqYPYW/7+B7sK32NCA7aaLwtnMjJr2fEbPtPBoWHLtpl17aeCj49iVB3mcW3E4Yrm/QxdPdXhIqSBoVE9XZ35ZHbueIgrJSSmgalSduhaK4Tz9USvSxQRgmYhwbGh9VGWxKSeBavjwLyo4RBD+/L/C7jBomGyNU5FOACB+7rnlltErijjUhrx4ZRsdDjYy8AMrJL49/dg+ZgnV2PT3khWW3yyShucaUT5xNpNNTxbwnEa+QCsTeDB5sdVwxpcggMcXIx8ozbBOFUqSpTpIWiNgIFmnT1l83kRo23FHZlygrBOZuANNdWX/W8+YLbmcGtkOgKQKBgQDvMLm9AvV2rRvj07LMue56fs6fs/nKOMsqczol5fYQKrwhCZaGg6OFCZ8ZKPZEKYM/dKpvT/N4YfsVJGRNNLPGYpS0vIOMHMV/p4i14WOMOuZxxzqAALK2kDHtkMlPckfnBAQp6EcDxiNyKqKvMomqwkyvS2ryEI7PM1K5GhQdRQKBgQC6IBLYR3Xpa5btvveBWP6GLdAgbqQ/RjGM8nVFpbLXGBa/B02JJbsa0gA5RyCm5UEJoyaxVju+39H1Dq0jW3iaPIsqsriLGTmrgmbYx918tT++emlFIYFV5NRJLpauX0Qo3zd3LTLnbAxtYEVa44v+EWoij9lRIM5PS8IzHEGCLwKBgQCnwifzTjj09HLkNp1oA1wko/2teyBN2cl8y3ZUEFalfiOWlE/zpi4w58+jaNxYcDkyb1P+YDfmDep5KJ4EnFseYBPmM3Wb9q36W3mB/0O/nav0zwPTtSmi671o3qyiwQd3GpUFA3mTRwujTg3uDOcLUd1Q8PdgMYbIAjoZwxWqdQKBgFVfkuVL2gUIicFhwAu/s3f+maHWvlYbr2zUZgBdYewRq5VSFzmaafmCbAHZ41tKewudn4jmYh9KcPb0FWzLb0VoEfmy4r1DA9XsyZoUCz9BsAyB/7lrBfVNMiajTRCMuCn7QWjT/a5zPDwLVaS8DSGsAT/7NZZl8twihuCEzHOXAoGAQOAk8iwE7wIMI8Pryp+WlEV6ss21ZV0YeFCoz0S3y/wzVmX8ZJqNCHwgoXKFDYRR9fP05ZgK25q8aqD+MdQJGAWx9QO9ujPo9orMQBc1+9bN1VaHsGGnRW/z51Rcm72SLrX1i8jNQ7MiSeZV8ehMdyIJIYE8UD9rc/SDhA9o03s=

client:
  secret: 66112208317904343747722374140985875840439492065673

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      CustomerByEmailCircuitBreaker:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
    instances:
      CustomerByEmailRetry:
        base-config: default
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true